---

language: ruby
dist: xenial
rvm:
  - 2.4.1

install: gem install jekyll html-proofer

before_script:
  - sed -i '/baseurl/d' dashboard/_config.yml

script: cd dashboard && jekyll build && htmlproofer ./_site --disable-external

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

sudo: false
cache: bundler
notifications:
  email: false

